baseurl = "https://pontsuyu.github.io/blog_template/"
theme = "hugo-gentoo-theme"
languageCode = "ja-jp"
title = "Blog Template"
# copyright = "Your Site copyright"
canonifyurls = true
paginate = 3
relativeurls = true
publishDir = "docs"
hasCJKLanguage = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  description = "Blog Template"
  author = "Hiroyuki"

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.global]]
    name = "Categories"
    url = "/categories/"

# [[menu.global]]
#     name = "Tags"
#     url = "/tags/"

# [[menu.footer]]
#     name = "About"
#     url = "/page/about/"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
